{% set version = "1.5.4" %}
{% set name = "mpfi" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://perso.ens-lyon.fr/nathalie.revol/softwares/mpfi-{{ version }}.tar.bz2
  sha256: d20ba56a8d57d0816f028be8b18a4aa909a068efcb9a260e69577939e4199752

build:
  number: 1002
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('mpfi', max_pin='x.x') }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - make

  host:
    - gmp
    - mpfr

  run:
    - gmp
    - mpfr

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}${SHLIB_EXT}  # [unix]

about:
  home: https://perso.ens-lyon.fr/nathalie.revol/software.html
  license: LGPL 3
  license_file: COPYING
  summary: A multiple precision interval arithmetic library based on MPFR
  dev_url: https://gitlab.inria.fr/mpfi/mpfi

extra:
  recipe-maintainers:
    - isuruf
    - marcelotrevisani
