{% set version = "1.5.3" %}
{% set name = "mpfi" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://gforge.inria.fr/frs/download.php/latestfile/181/{{ name }}-{{ version }}.tar.gz
  sha256: beed2003fdbedf590e8dd6edb4f2321e609e329df99ed4139cd66d7ebbc41240

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('mpfi', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
  host:
    - gmp
    - mpfr
  run:
    - gmp
    - mpfr

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://mpfi.gforge.inria.fr/
  license: LGPL 3
  license_file: {{ SRC_DIR }}/COPYING
  summary: A multiple precision interval arithmetic library based on MPFR
  dev_url: https://gforge.inria.fr/scm/?group_id=157

extra:
  recipe-maintainers:
    - isuruf
